// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
// import "./train"
// import "./cloud"
// import "./scroll"
// import "./checkbox"
// import "./post-it"
// import "./tv"
// import "./hobbies"
